spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/licheng?serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: licheng-backend
  # session失效时间 (分钟)
  session:
    timeout: 86400
  # redis 配置
  data:
    redis:
      port: 6379
      host: localhost
      database: 1
server:
  port: 8080
  servlet:
    context-path: /api
#    这里domain: localhost加不加都可以
#    session:
#      cookie:
#        domain: localhost
mybatis-plus:
  configuration:
    #    数据库用的驼峰非下划线，关闭下划线转驼峰
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)